name: CI for Self-Hosted Runner

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
      - name: Run a script
        run: echo "This is a job running on the self-hosted runner."
